"use client";

import Link from "next/link";
import { Boxes, Building2, FileText, ReceiptText, Search, Settings, ShieldCheck, ShoppingCart } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useBusinessPortal } from "./PortalContext";
import { PageHeader, StatusBadge, Surface } from "./PortalPrimitives";

export function BusinessCatalogPage() {
  return <><PageHeader eyebrow="Corporate commerce" title="Product catalog" description="Browse the verified technology catalog, then request volume or contract pricing." /><Surface className="overflow-hidden"><div className="grid gap-8 bg-gradient-to-br from-slate-950 to-blue-950 p-6 text-white sm:p-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="inline-flex rounded-full border border-blue-400/30 bg-blue-400/10 px-3 py-1 text-xs font-semibold text-blue-200">Business pricing ready</span><h2 className="mt-4 max-w-2xl text-2xl font-bold sm:text-3xl">Source laptops, components, networking and office technology from one catalog.</h2><p className="mt-3 max-w-2xl text-sm text-slate-300">Public prices remain visible; eligible contract and tier pricing is applied by the existing business pricing engine.</p></div><Boxes className="hidden size-28 text-blue-400/50 lg:block" /></div><div className="p-5 sm:p-6"><form action="/ecommerce/products" className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search product catalog</span><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input name="q" className="h-11 pl-9" placeholder="Search product, brand, SKU or model…" /></label><Button type="submit" className="h-11">Search catalog</Button></form><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button asChild variant="outline" className="h-auto justify-start p-4"><Link href="/ecommerce/products"><ShoppingCart className="size-5 text-blue-600" /><span className="text-left"><span className="block font-semibold">Browse all products</span><span className="block text-xs font-normal text-muted-foreground">Compare available configurations</span></span></Link></Button><Button asChild variant="outline" className="h-auto justify-start p-4"><Link href="/business/rfqs/new"><FileText className="size-5 text-blue-600" /><span className="text-left"><span className="block font-semibold">Request volume pricing</span><span className="block text-xs font-normal text-muted-foreground">Create a multi-line RFQ</span></span></Link></Button></div></div></Surface></>;
}

export function PaymentsPage() {
  return <><PageHeader eyebrow="Finance" title="Payments" description="Payment activity remains tied to the source order and its immutable credit ledger records." /><div className="grid gap-5 md:grid-cols-2"><Surface className="p-6"><ReceiptText className="size-8 text-blue-600" /><h2 className="mt-5 text-lg font-semibold">Invoice payments</h2><p className="mt-2 text-sm text-muted-foreground">Review payment state, method and transaction reference for each invoice.</p><Button asChild variant="outline" className="mt-5"><Link href="/business/invoices">View invoices</Link></Button></Surface><Surface className="p-6"><ShieldCheck className="size-8 text-blue-600" /><h2 className="mt-5 text-lg font-semibold">Credit movements</h2><p className="mt-2 text-sm text-muted-foreground">Charges, repayments and adjustments are recorded in the corporate statement.</p><Button asChild variant="outline" className="mt-5"><Link href="/business/credit/statement">View statement</Link></Button></Surface></div></>;
}

export function SettingsPage() {
  const context = useBusinessPortal(); const membership = context.activeMembership;
  return <><PageHeader eyebrow="Business portal" title="Settings" description="Review the active portal context and organization access policy." /><div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Surface className="p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-300"><Building2 className="size-5" /></span><div><h2 className="font-semibold">Active organization</h2><p className="text-sm text-muted-foreground">{membership.organization.displayName || membership.organization.legalName}</p></div></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><Item label="Organization code" value={membership.organization.code} /><Item label="Currency" value={membership.organization.currency} /><Item label="Country" value={membership.organization.country} /><Item label="Member ID" value={membership.memberId} /></dl></Surface><Surface className="p-6"><div className="flex items-center gap-3"><Settings className="size-5 text-blue-600" /><h2 className="font-semibold">Access summary</h2></div><div className="mt-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Roles</p><div className="mt-2 flex flex-wrap gap-2">{membership.roles.map((role) => <StatusBadge key={role} status={role} />)}</div></div><div className="mt-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Capabilities</p><div className="mt-2 flex flex-wrap gap-2">{membership.activeCapabilities.map((capability) => <StatusBadge key={capability} status={capability} />)}</div></div><p className="mt-6 rounded-xl bg-muted p-4 text-xs text-muted-foreground">Permissions are derived server-side from both roles and active capabilities. Hidden navigation does not replace API authorization.</p></Surface></div></>;
}

function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-all text-sm font-medium">{value}</dd></div>; }
