import type {
  StorefrontBrandSeed,
  StorefrontCategorySeed,
  StorefrontProductSeed,
} from "./types";

const PRODUCT_ROOT = "/upload/products";
const GALLERY_ROOT = `${PRODUCT_ROOT}/gallery`;

export const STOREFRONT_CATEGORIES: StorefrontCategorySeed[] = [
  { key: "laptop", name: "Laptop", slug: "laptop", image: `${PRODUCT_ROOT}/1772530126044-hp-laptop-victus-gaming-15-fb3180ax-cover.webp` },
  { key: "laptop_gaming", name: "Gaming Laptop", slug: "gaming-laptop", image: `${PRODUCT_ROOT}/1772530126044-hp-laptop-victus-gaming-15-fb3180ax-cover.webp`, parentKey: "laptop" },
  { key: "laptop_business", name: "Business Laptop", slug: "business-laptop", image: `${PRODUCT_ROOT}/1772530665816-lenovo-laptop-thinkpad-e14-gen-7-cover.webp`, parentKey: "laptop" },
  { key: "laptop_convertible", name: "Convertible Laptop", slug: "convertible-laptop", image: `${PRODUCT_ROOT}/1772530279644-hp-laptop-omnibook-5-flip-x360-14-fp0133tu-cover.webp`, parentKey: "laptop" },
  { key: "laptop_budget", name: "Budget Laptop", slug: "budget-laptop", image: `${PRODUCT_ROOT}/1772529933080-herobook-pro-1-500x500.jpg`, parentKey: "laptop" },
  { key: "desktop", name: "Desktop PC", slug: "desktop-pc", image: `${PRODUCT_ROOT}/1772530789360-amd-gaming-pc-amd-ryzen-5-7500f-gaming-desktop-pc-cover.webp` },
  { key: "desktop_gaming", name: "Gaming Desktop", slug: "gaming-desktop", image: `${PRODUCT_ROOT}/1772530789360-amd-gaming-pc-amd-ryzen-5-7500f-gaming-desktop-pc-cover.webp`, parentKey: "desktop" },
  { key: "desktop_office", name: "Office Desktop", slug: "office-desktop", image: `${PRODUCT_ROOT}/1772530900103-amd-gaming-pc-amd-ryzen-5-pc-cover.webp`, parentKey: "desktop" },
  { key: "desktop_creator", name: "Creator PC", slug: "creator-pc", image: `${PRODUCT_ROOT}/1772531070896-amd-gaming-pc-amd-ryzen-7-7700-pc-cover.webp`, parentKey: "desktop" },
  { key: "components", name: "Components", slug: "components", image: `${PRODUCT_ROOT}/1773131036391-amd-processor-ryzen-7-9850x3d-cover.webp` },
  { key: "processor", name: "Processor", slug: "processor", image: `${PRODUCT_ROOT}/1773131036391-amd-processor-ryzen-7-9850x3d-cover.webp`, parentKey: "components" },
  { key: "storage", name: "SSD & Storage", slug: "ssd-storage", image: `${PRODUCT_ROOT}/1773131710707-corsair-ssd-mp600-pro-xt-cover.webp`, parentKey: "components" },
  { key: "power", name: "Power Supply", slug: "power-supply", image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp`, parentKey: "components" },
  { key: "motherboard", name: "Motherboard", slug: "motherboard", image: `${PRODUCT_ROOT}/1773131036391-amd-processor-ryzen-7-9850x3d-cover.webp`, parentKey: "components" },
  { key: "ram", name: "Desktop RAM", slug: "desktop-ram", image: `${PRODUCT_ROOT}/1773131710707-corsair-ssd-mp600-pro-xt-cover.webp`, parentKey: "components" },
  { key: "graphics", name: "Graphics Card", slug: "graphics-card", image: `${PRODUCT_ROOT}/1772530789360-amd-gaming-pc-amd-ryzen-5-7500f-gaming-desktop-pc-cover.webp`, parentKey: "components" },
  { key: "accessories", name: "Accessories", slug: "accessories", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp` },
  { key: "keyboard", name: "Keyboard", slug: "keyboard", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "mouse", name: "Mouse", slug: "mouse", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "headset", name: "Headphone & Headsets", slug: "headphone-headsets", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "webcam", name: "WebCam", slug: "webcam", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "accessories" },
  { key: "microphone", name: "Microphone", slug: "microphone", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "mousepad", name: "Mouse Pad", slug: "mouse-pad", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "docking", name: "Docking Station", slug: "docking-station", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "gamepad", name: "Gamepad", slug: "gamepad", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "pendrive", name: "Pen Drive", slug: "pen-drive", image: `${PRODUCT_ROOT}/1773131710707-corsair-ssd-mp600-pro-xt-cover.webp`, parentKey: "accessories" },
  { key: "memorycard", name: "Memory Card", slug: "memory-card", image: `${PRODUCT_ROOT}/1773131710707-corsair-ssd-mp600-pro-xt-cover.webp`, parentKey: "accessories" },
  { key: "powerbank", name: "Power Bank", slug: "power-bank", image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp`, parentKey: "accessories" },
  { key: "thermal", name: "Thermal Paste", slug: "thermal-paste", image: `${PRODUCT_ROOT}/1773131036391-amd-processor-ryzen-7-9850x3d-cover.webp`, parentKey: "accessories" },
  { key: "capture", name: "Capture Card", slug: "capture-card", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "accessories" },
  { key: "powerstrip", name: "Power Strip", slug: "power-strip", image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp`, parentKey: "accessories" },
  { key: "cable", name: "Cable & Converter", slug: "cable-converter", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "cable_hdmi", name: "HDMI Cable", slug: "hdmi-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_displayport", name: "DisplayPort Cable", slug: "displayport-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_usb", name: "USB Cable", slug: "usb-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_type_c", name: "USB Type-C Cable", slug: "usb-type-c-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_vga_dvi", name: "VGA & DVI Cable", slug: "vga-dvi-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_audio", name: "Audio Cable", slug: "audio-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_network", name: "Network Cable", slug: "network-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_power", name: "Power Cable", slug: "power-cable", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "cable_adapter", name: "Converter & Adapter", slug: "converter-adapter", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "cable" },
  { key: "hubs", name: "HUB & Splitters", slug: "hub-splitters", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "keycaps", name: "Keycaps", slug: "keycaps", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "accessories" },
  { key: "cardreader", name: "Card Reader", slug: "card-reader", image: `${PRODUCT_ROOT}/1773131710707-corsair-ssd-mp600-pro-xt-cover.webp`, parentKey: "accessories" },
  { key: "monitor", name: "Monitor", slug: "monitor", image: `${PRODUCT_ROOT}/1773201015138-geesuu-monitor-blazewheel-mg270l2q-cover.webp` },
  { key: "monitor_gaming", name: "Gaming Monitor", slug: "gaming-monitor", image: `${PRODUCT_ROOT}/1773201015138-geesuu-monitor-blazewheel-mg270l2q-cover.webp`, parentKey: "monitor" },
  { key: "monitor_business", name: "Business Monitor", slug: "business-monitor", image: `${PRODUCT_ROOT}/1773201015138-geesuu-monitor-blazewheel-mg270l2q-cover.webp`, parentKey: "monitor" },
  { key: "networking", name: "Networking", slug: "networking", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg` },
  { key: "router", name: "Router", slug: "router", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "networking" },
  { key: "switch", name: "Network Switch", slug: "network-switch", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "networking" },
  { key: "office", name: "Office Equipment", slug: "office-equipment", image: `${PRODUCT_ROOT}/1773129714167-epson-printers-lq-690ii-cover.webp` },
  { key: "printer", name: "Printer", slug: "printer", image: `${PRODUCT_ROOT}/1773129714167-epson-printers-lq-690ii-cover.webp`, parentKey: "office" },
  { key: "scanner", name: "Scanner", slug: "scanner", image: `${PRODUCT_ROOT}/1773129714167-epson-printers-lq-690ii-cover.webp`, parentKey: "office" },
  { key: "gadget", name: "Gadgets", slug: "smart-gadget", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg` },
  { key: "drone", name: "Camera Drone", slug: "camera-drone", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "gadget" },
  { key: "smartwatch", name: "Smart Watch", slug: "smart-watch", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "gadget" },
  { key: "cameras", name: "Cameras", slug: "cameras", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg` },
  { key: "actioncamera", name: "Action Camera", slug: "action-camera", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "cameras" },
  { key: "securitycamera", name: "Security Camera", slug: "security-camera", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "cameras" },
  { key: "tv", name: "TV & Sound", slug: "television", image: `${PRODUCT_ROOT}/1772430670432-TV11.jpg` },
  { key: "smarttv", name: "Smart TV", slug: "smart-tv", image: `${PRODUCT_ROOT}/1772430670432-TV11.jpg`, parentKey: "tv" },
  { key: "speaker", name: "Speaker", slug: "speaker", image: `${PRODUCT_ROOT}/1772430670432-TV11.jpg`, parentKey: "tv" },
  { key: "power_solution", name: "Power", slug: "power", image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp` },
  { key: "ups", name: "UPS", slug: "ups", image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp`, parentKey: "power_solution" },
  { key: "ips", name: "IPS", slug: "ips", image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp`, parentKey: "power_solution" },
  { key: "security", name: "Security", slug: "security", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg` },
  { key: "cctv", name: "CCTV System", slug: "cctv-system", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "security" },
  { key: "accesscontrol", name: "Access Control", slug: "access-control", image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, parentKey: "security" },
  { key: "gaming", name: "Gaming", slug: "gaming", image: `${PRODUCT_ROOT}/1773129366033-electron-gaming-chair-valiant-cover.webp` },
  { key: "chair", name: "Gaming Chair", slug: "gaming-chair", image: `${PRODUCT_ROOT}/1773129366033-electron-gaming-chair-valiant-cover.webp`, parentKey: "gaming" },
  { key: "console", name: "Gaming Console", slug: "gaming-console", image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, parentKey: "gaming" },
  { key: "appliance", name: "Appliance", slug: "home-appliance", image: `${PRODUCT_ROOT}/1773128954247-konka-geyser-kd-60d1c1-cover.webp` },
  { key: "waterheater", name: "Water Heater", slug: "water-heater", image: `${PRODUCT_ROOT}/1773128954247-konka-geyser-kd-60d1c1-cover.webp`, parentKey: "appliance" },
  { key: "software", name: "Software", slug: "software", image: `${PRODUCT_ROOT}/1772529933080-herobook-pro-1-500x500.jpg` },
  { key: "os", name: "Operating System", slug: "operating-system", image: `${PRODUCT_ROOT}/1772529933080-herobook-pro-1-500x500.jpg`, parentKey: "software" },
  { key: "antivirus", name: "Antivirus", slug: "antivirus", image: `${PRODUCT_ROOT}/1772529933080-herobook-pro-1-500x500.jpg`, parentKey: "software" },
  { key: "servers", name: "Servers", slug: "servers", image: `${PRODUCT_ROOT}/1772531070896-amd-gaming-pc-amd-ryzen-7-7700-pc-cover.webp` },
  { key: "rackserver", name: "Rack Server", slug: "rack-server", image: `${PRODUCT_ROOT}/1772531070896-amd-gaming-pc-amd-ryzen-7-7700-pc-cover.webp`, parentKey: "servers" },
  { key: "serveraccessory", name: "Server Accessories", slug: "server-accessories", image: `${PRODUCT_ROOT}/1772531070896-amd-gaming-pc-amd-ryzen-7-7700-pc-cover.webp`, parentKey: "servers" },
];

export const STOREFRONT_BRANDS: StorefrontBrandSeed[] = [
  { key: "chuwi", name: "CHUWI", slug: "chuwi" },
  { key: "hp", name: "HP", slug: "hp" },
  { key: "lenovo", name: "Lenovo", slug: "lenovo" },
  { key: "amd", name: "AMD", slug: "amd" },
  { key: "corsair", name: "Corsair", slug: "corsair" },
  { key: "acer", name: "Acer", slug: "acer" },
  { key: "pcpower", name: "PC Power", slug: "pc-power" },
  { key: "geesuu", name: "Geesuu", slug: "geesuu" },
  { key: "epson", name: "Epson", slug: "epson" },
  { key: "electron", name: "Electron", slug: "electron" },
  { key: "gamedias", name: "Gamedias", slug: "gamedias" },
  { key: "konka", name: "Konka", slug: "konka" },
  { key: "techvision", name: "TechVision", slug: "techvision" },
  { key: "skyview", name: "SkyView", slug: "skyview" },
  { key: "aerocam", name: "AeroCam", slug: "aerocam" },
];

const standardVariant = (
  sku: string,
  price: number,
  stock: number,
  costPrice: number,
) => [{ sku, price, stock, costPrice, options: {}, isDefault: true }];

export const STOREFRONT_PRODUCTS: StorefrontProductSeed[] = [
  {
    key: "herobook", name: "CHUWI HeroBook Pro 14.1-inch Laptop", slug: "chuwi-herobook-pro-14-laptop", sku: "DEMO-LAP-CHUWI-001", categoryKey: "laptop_budget", brandKey: "chuwi",
    shortDesc: "Slim everyday laptop with 8GB RAM and 256GB SSD.",
    description: "A lightweight everyday notebook for study, office applications, video calls and web browsing. The full-HD display, SSD storage and long-lasting battery make it a practical entry-level laptop.",
    basePrice: 29990, originalPrice: 32990, image: `${PRODUCT_ROOT}/1772529933080-herobook-pro-1-500x500.jpg`, featured: true, soldCount: 48, weight: 1.39,
    specs: { Processor: "Intel Celeron N4020", RAM: "8GB LPDDR4", Storage: "256GB SSD", Display: "14.1-inch Full HD IPS", Graphics: "Intel UHD 600", "Operating System": "Windows 11", Warranty: "1 Year" },
    variants: standardVariant("DEMO-LAP-CHUWI-001-8-256", 29990, 18, 25100),
  },
  {
    key: "victus", name: "HP Victus 15 Ryzen 5 Gaming Laptop", slug: "hp-victus-15-ryzen-5-gaming-laptop", sku: "DEMO-LAP-HP-001", categoryKey: "laptop_gaming", brandKey: "hp",
    shortDesc: "Ryzen 5 gaming laptop with RTX graphics and 144Hz display.",
    description: "Built for smooth 1080p gaming and creative workloads, this Victus combines an AMD Ryzen processor, dedicated RTX graphics, fast NVMe storage and a high-refresh display in a clean, professional chassis.",
    basePrice: 89900, originalPrice: 94900, image: `${PRODUCT_ROOT}/1772530126044-hp-laptop-victus-gaming-15-fb3180ax-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530133342-hp-laptop-victus-gaming-15-fb3180ax-picture-1.webp`, `${GALLERY_ROOT}/1772530133341-hp-laptop-victus-gaming-15-fb3180ax-picture-2.webp`, `${GALLERY_ROOT}/1772530133341-hp-laptop-victus-gaming-15-fb3180ax-picture-3.webp`], featured: true, soldCount: 73, weight: 2.29,
    specs: { Processor: "AMD Ryzen 5 8645HS", RAM: "16GB DDR5", Storage: "512GB NVMe SSD", Display: "15.6-inch FHD 144Hz", Graphics: "NVIDIA GeForce RTX 4050 6GB", "Operating System": "Windows 11", Warranty: "2 Years" },
    variants: [
      { sku: "DEMO-LAP-HP-001-16-512", price: 89900, costPrice: 80500, stock: 12, options: { RAM: "16GB", Storage: "512GB" }, isDefault: true },
      { sku: "DEMO-LAP-HP-001-16-1TB", price: 96900, costPrice: 86500, stock: 7, options: { RAM: "16GB", Storage: "1TB" } },
    ],
  },
  {
    key: "omnibook13", name: "HP OmniBook 5 Flip 14 fp0133TU", slug: "hp-omnibook-5-flip-14-fp0133tu", sku: "DEMO-LAP-HP-002", categoryKey: "laptop_convertible", brandKey: "hp",
    shortDesc: "Convertible AI-ready laptop with touchscreen and versatile 360-degree hinge.",
    description: "A flexible two-in-one laptop for work, presentation and entertainment. Use it as a traditional notebook or fold the touch display into tent and tablet modes.",
    basePrice: 109500, originalPrice: 115000, image: `${PRODUCT_ROOT}/1772530279644-hp-laptop-omnibook-5-flip-x360-14-fp0133tu-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530287402-hp-laptop-omnibook-5-flip-x360-14-fp0133tu-picture-1.webp`, `${GALLERY_ROOT}/1772530287402-hp-laptop-omnibook-5-flip-x360-14-fp0133tu-picture-2.webp`, `${GALLERY_ROOT}/1772530287402-hp-laptop-omnibook-5-flip-x360-14-fp0133tu-picture-3.webp`], featured: true, soldCount: 31, weight: 1.62,
    specs: { Processor: "Intel Core Ultra 5", RAM: "16GB LPDDR5x", Storage: "512GB NVMe SSD", Display: "14-inch 2K Touch", Graphics: "Intel Arc", "Operating System": "Windows 11", Warranty: "2 Years" },
    variants: standardVariant("DEMO-LAP-HP-002-16-512", 109500, 9, 98800),
  },
  {
    key: "omnibook14", name: "HP OmniBook 5 Flip 14 fp0134TU", slug: "hp-omnibook-5-flip-14-fp0134tu", sku: "DEMO-LAP-HP-003", categoryKey: "laptop_convertible", brandKey: "hp",
    shortDesc: "Premium 2K touch convertible with 1TB SSD.",
    description: "This higher-capacity OmniBook Flip offers a sharp touch display, responsive performance and all-day portability for professionals who want a laptop and tablet in one device.",
    basePrice: 124900, originalPrice: 131000, image: `${PRODUCT_ROOT}/1772530416912-hp-laptop-omnibook-5-flip-14-fp0134tu-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530424708-hp-laptop-omnibook-5-flip-14-fp0134tu-picture-1.webp`, `${GALLERY_ROOT}/1772530424710-hp-laptop-omnibook-5-flip-14-fp0134tu-picture-2.webp`, `${GALLERY_ROOT}/1772530424708-hp-laptop-omnibook-5-flip-14-fp0134tu-picture-3.webp`], soldCount: 19, weight: 1.62,
    specs: { Processor: "Intel Core Ultra 7", RAM: "16GB LPDDR5x", Storage: "1TB NVMe SSD", Display: "14-inch 2K Touch", Graphics: "Intel Arc", "Operating System": "Windows 11", Warranty: "2 Years" },
    variants: standardVariant("DEMO-LAP-HP-003-16-1TB", 124900, 6, 113000),
  },
  {
    key: "thinkpad", name: "Lenovo ThinkPad E14 Gen 7 Business Laptop", slug: "lenovo-thinkpad-e14-gen-7", sku: "DEMO-LAP-LEN-001", categoryKey: "laptop_business", brandKey: "lenovo",
    shortDesc: "Durable business laptop with a comfortable keyboard and strong security.",
    description: "A dependable business notebook with modern connectivity, a spill-resistant keyboard, hardware security and straightforward serviceability for office teams.",
    basePrice: 98500, originalPrice: 103500, image: `${PRODUCT_ROOT}/1772530665816-lenovo-laptop-thinkpad-e14-gen-7-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530675939-lenovo-laptop-thinkpad-e14-gen-7-picture-1.webp`, `${GALLERY_ROOT}/1772530675938-lenovo-laptop-thinkpad-e14-gen-7-picture-2.webp`, `${GALLERY_ROOT}/1772530675969-lenovo-laptop-thinkpad-e14-gen-7-picture-3.webp`], featured: true, soldCount: 56, weight: 1.44,
    specs: { Processor: "Intel Core Ultra 5", RAM: "16GB DDR5", Storage: "512GB NVMe SSD", Display: "14-inch WUXGA IPS", Graphics: "Intel Graphics", "Operating System": "Windows 11 Pro", Warranty: "3 Years" },
    variants: standardVariant("DEMO-LAP-LEN-001-16-512", 98500, 14, 89000),
  },
  {
    key: "pc7500f", name: "AMD Ryzen 5 7500F RTX Gaming Desktop", slug: "amd-ryzen-5-7500f-rtx-gaming-desktop", sku: "DEMO-PC-AMD-001", categoryKey: "desktop_gaming", brandKey: "amd",
    shortDesc: "Balanced AM5 gaming desktop for high-frame-rate 1080p play.",
    description: "A ready-to-play gaming desktop featuring the Ryzen 5 7500F platform, dedicated graphics, dual-channel memory and a fast NVMe SSD. Components are selected for a clear future upgrade path.",
    basePrice: 84900, originalPrice: 89900, image: `${PRODUCT_ROOT}/1772530789360-amd-gaming-pc-amd-ryzen-5-7500f-gaming-desktop-pc-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530793841-amd-gaming-pc-amd-ryzen-5-7500f-gaming-desktop-pc-cover.webp`], featured: true, soldCount: 64, weight: 9.5,
    specs: { Processor: "AMD Ryzen 5 7500F", RAM: "16GB DDR5", Storage: "1TB NVMe SSD", Graphics: "NVIDIA GeForce RTX 4060 8GB", Power: "650W 80+ Bronze", Warranty: "3 Years Service" },
    variants: standardVariant("DEMO-PC-AMD-001-16-1TB", 84900, 10, 76200),
  },
  {
    key: "pc5600g", name: "AMD Ryzen 5 5600G Budget Desktop PC", slug: "amd-ryzen-5-5600g-budget-desktop", sku: "DEMO-PC-AMD-002", categoryKey: "desktop_office", brandKey: "amd",
    shortDesc: "Affordable complete tower for office, study and casual gaming.",
    description: "A value-focused desktop powered by integrated Radeon graphics. It is a practical choice for office work, learning, browsing and esports titles, with room to add a graphics card later.",
    basePrice: 38900, originalPrice: 41500, image: `${PRODUCT_ROOT}/1772530900103-amd-gaming-pc-amd-ryzen-5-pc-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530905740-amd-gaming-pc-amd-ryzen-5-pc-cover.webp`], soldCount: 82, weight: 7.2,
    specs: { Processor: "AMD Ryzen 5 5600G", RAM: "16GB DDR4", Storage: "512GB NVMe SSD", Graphics: "Radeon Integrated Graphics", Power: "500W", Warranty: "3 Years Service" },
    variants: standardVariant("DEMO-PC-AMD-002-16-512", 38900, 20, 34200),
  },
  {
    key: "pc7600x", name: "AMD Ryzen 5 7600X Performance Desktop", slug: "amd-ryzen-5-7600x-performance-desktop", sku: "DEMO-PC-AMD-003", categoryKey: "desktop_creator", brandKey: "amd",
    shortDesc: "High-performance AM5 desktop for gaming and content creation.",
    description: "A performance desktop tuned for modern games, streaming and content creation with DDR5 memory, a fast processor and efficient airflow.",
    basePrice: 114500, originalPrice: 121000, image: `${PRODUCT_ROOT}/1772530969562-amd-gaming-pc-md-ryzen-5-7600x-desktop-pc-cover.webp`, gallery: [`${GALLERY_ROOT}/1772530975041-amd-gaming-pc-md-ryzen-5-7600x-desktop-pc-cover.webp`], featured: true, soldCount: 29, weight: 10.2,
    specs: { Processor: "AMD Ryzen 5 7600X", RAM: "32GB DDR5", Storage: "1TB Gen4 NVMe SSD", Graphics: "NVIDIA GeForce RTX 4060 Ti", Power: "750W 80+ Gold", Warranty: "3 Years Service" },
    variants: standardVariant("DEMO-PC-AMD-003-32-1TB", 114500, 8, 103000),
  },
  {
    key: "pc7700", name: "AMD Ryzen 7 7700 Creator Desktop", slug: "amd-ryzen-7-7700-creator-desktop", sku: "DEMO-PC-AMD-004", categoryKey: "desktop_creator", brandKey: "amd",
    shortDesc: "Eight-core creator workstation with powerful RTX graphics.",
    description: "A fast creator-focused desktop for editing, rendering, development and gaming. The eight-core CPU and ample memory keep demanding multitasking responsive.",
    basePrice: 145000, originalPrice: 153000, image: `${PRODUCT_ROOT}/1772531070896-amd-gaming-pc-amd-ryzen-7-7700-pc-cover.webp`, gallery: [`${GALLERY_ROOT}/1772531075662-amd-gaming-pc-amd-ryzen-7-7700-pc-cover.webp`], soldCount: 17, weight: 11.1,
    specs: { Processor: "AMD Ryzen 7 7700", RAM: "32GB DDR5", Storage: "2TB Gen4 NVMe SSD", Graphics: "NVIDIA GeForce RTX 4070", Power: "750W 80+ Gold", Warranty: "3 Years Service" },
    variants: standardVariant("DEMO-PC-AMD-004-32-2TB", 145000, 5, 131000),
  },
  {
    key: "pc8500g", name: "AMD Ryzen 5 8500G Smart Desktop PC", slug: "amd-ryzen-5-8500g-smart-desktop", sku: "DEMO-PC-AMD-005", categoryKey: "desktop_office", brandKey: "amd",
    shortDesc: "Modern AM5 desktop with capable integrated Radeon graphics.",
    description: "A compact, energy-efficient AM5 system for home and business use. Integrated Radeon graphics handle daily visual work and casual games without requiring a separate GPU.",
    basePrice: 52900, originalPrice: 55900, image: `${PRODUCT_ROOT}/1772531141081-amd-gaming-pc-amd-ryzen-5-8500g-desktop-pc-cover.webp`, gallery: [`${GALLERY_ROOT}/1772531146447-amd-gaming-pc-amd-ryzen-5-8500g-desktop-pc-cover.webp`], soldCount: 41, weight: 7.5,
    specs: { Processor: "AMD Ryzen 5 8500G", RAM: "16GB DDR5", Storage: "512GB NVMe SSD", Graphics: "AMD Radeon 740M", Power: "550W 80+ Bronze", Warranty: "3 Years Service" },
    variants: standardVariant("DEMO-PC-AMD-005-16-512", 52900, 15, 47100),
  },
  {
    key: "processor9850", name: "AMD Ryzen 7 9850X3D Gaming Processor", slug: "amd-ryzen-7-9850x3d-processor", sku: "DEMO-CPU-AMD-001", categoryKey: "processor", brandKey: "amd",
    shortDesc: "High-end eight-core gaming CPU with 3D V-Cache technology.",
    description: "A flagship gaming processor designed for high frame rates and low latency. The large 3D V-Cache helps gaming workloads while the eight-core design remains capable for productivity.",
    basePrice: 64900, originalPrice: 68500, image: `${PRODUCT_ROOT}/1773131036391-amd-processor-ryzen-7-9850x3d-cover.webp`, gallery: [`${GALLERY_ROOT}/1773131040618-amd-processor-ryzen-7-9850x3d-picture-1.webp`], featured: true, soldCount: 24, weight: 0.12,
    specs: { Processor: "8 Cores / 16 Threads", "Base Clock": "4.7GHz", "Boost Clock": "Up to 5.6GHz", "Cache": "104MB", "Socket": "AM5", Warranty: "3 Years" },
    variants: standardVariant("DEMO-CPU-AMD-001-BOX", 64900, 13, 58700),
  },
  {
    key: "ssd", name: "Corsair MP600 Pro XT 1TB NVMe SSD", slug: "corsair-mp600-pro-xt-1tb-ssd", sku: "DEMO-SSD-COR-001", categoryKey: "storage", brandKey: "corsair",
    shortDesc: "High-speed PCIe 4.0 NVMe SSD with integrated heatsink.",
    description: "Upgrade load times and file transfers with a fast PCIe Gen4 SSD. Its aluminum heatsink helps sustain performance during long gaming and creator workloads.",
    basePrice: 12900, originalPrice: 14500, image: `${PRODUCT_ROOT}/1773131710707-corsair-ssd-mp600-pro-xt-cover.webp`, gallery: [`${GALLERY_ROOT}/1773131717317-corsair-ssd-mp600-pro-xt-picture-1.webp`], featured: true, soldCount: 112, weight: 0.07,
    specs: { Capacity: "1TB", Interface: "PCIe Gen4 x4 NVMe", "Read Speed": "Up to 7,100MB/s", "Write Speed": "Up to 5,800MB/s", "Form Factor": "M.2 2280", Warranty: "5 Years" },
    variants: [
      { sku: "DEMO-SSD-COR-001-1TB", price: 12900, costPrice: 10800, stock: 32, options: { Capacity: "1TB" }, isDefault: true },
      { sku: "DEMO-SSD-COR-001-2TB", price: 22900, costPrice: 19400, stock: 16, options: { Capacity: "2TB" } },
    ],
  },
  {
    key: "psu", name: "Acer AC-1000 1000W 80+ Gold Power Supply", slug: "acer-ac-1000-1000w-power-supply", sku: "DEMO-PSU-ACE-001", categoryKey: "power", brandKey: "acer",
    shortDesc: "Fully modular 1000W power supply for high-performance PCs.",
    description: "A high-capacity modular power supply for powerful gaming and workstation builds, featuring efficient power delivery, quiet cooling and comprehensive protection circuits.",
    basePrice: 15900, originalPrice: 17500, image: `${PRODUCT_ROOT}/1772345783053-acer-power-supply-ac-1000-cover.webp`, gallery: [`${GALLERY_ROOT}/1772345787755-acer-power-supply-ac-1000-picture-1.webp`], soldCount: 38, weight: 2.1,
    specs: { Power: "1000W", Efficiency: "80 Plus Gold", Modularity: "Fully Modular", "Fan Size": "135mm", Protection: "OVP / OCP / SCP / OTP", Warranty: "10 Years" },
    variants: standardVariant("DEMO-PSU-ACE-001-BK", 15900, 21, 13500),
  },
  {
    key: "keyboard", name: "PC Power K87 RGB Mechanical Keyboard", slug: "pc-power-k87-rgb-mechanical-keyboard", sku: "DEMO-KB-PCP-001", categoryKey: "keyboard", brandKey: "pcpower",
    shortDesc: "Compact TKL mechanical keyboard with customizable RGB lighting.",
    description: "A compact mechanical keyboard for gaming and everyday typing. The tenkeyless layout saves desk space while dedicated lighting modes add personality to the setup.",
    basePrice: 3490, originalPrice: 3990, image: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp`, gallery: [`${GALLERY_ROOT}/1772531236895-pc-power-keyboard-k87-rgb-picture-1.webp`], featured: true, soldCount: 156, weight: 0.82,
    specs: { Layout: "87-key TKL", Switch: "Mechanical Red", Connectivity: "USB Type-C", Lighting: "RGB", "Polling Rate": "1000Hz", Warranty: "1 Year" },
    variants: [
      { sku: "DEMO-KB-PCP-001-BLK", price: 3490, costPrice: 2710, stock: 45, options: { Color: "Black" }, isDefault: true, colorImage: `${PRODUCT_ROOT}/1772531232004-pc-power-keyboard-k87-rgb-cover.webp` },
      { sku: "DEMO-KB-PCP-001-WHT", price: 3690, costPrice: 2860, stock: 28, options: { Color: "White" }, colorImage: `${GALLERY_ROOT}/1772531236895-pc-power-keyboard-k87-rgb-picture-1.webp` },
    ],
  },
  {
    key: "monitor", name: "Geesuu Blazewheel MG270L2Q 27-inch QHD Monitor", slug: "geesuu-blazewheel-mg270l2q-monitor", sku: "DEMO-MON-GEE-001", categoryKey: "monitor_gaming", brandKey: "geesuu",
    shortDesc: "27-inch QHD IPS gaming monitor with high refresh rate.",
    description: "A sharp QHD gaming display with fluid motion, wide viewing angles and adaptive sync support. It is equally comfortable for competitive games, creative work and a spacious office setup.",
    basePrice: 28900, originalPrice: 31500, image: `${PRODUCT_ROOT}/1773201015138-geesuu-monitor-blazewheel-mg270l2q-cover.webp`, gallery: [`${GALLERY_ROOT}/1773201021491-geesuu-monitor-blazewheel-mg270l2q-picture-1.webp`, `${GALLERY_ROOT}/1773201021451-geesuu-monitor-blazewheel-mg270l2q-picture-2.webp`, `${GALLERY_ROOT}/1773201021451-geesuu-monitor-blazewheel-mg270l2q-picture-3.webp`], featured: true, soldCount: 67, weight: 5.1,
    specs: { Display: "27-inch IPS", Resolution: "2560 x 1440 QHD", "Refresh Rate": "180Hz", "Response Time": "1ms", Connectivity: "HDMI / DisplayPort", Warranty: "3 Years" },
    variants: standardVariant("DEMO-MON-GEE-001-27", 28900, 17, 24800),
  },
  {
    key: "printer", name: "Epson LQ-690II Dot Matrix Printer", slug: "epson-lq-690ii-dot-matrix-printer", sku: "DEMO-PRN-EPS-001", categoryKey: "printer", brandKey: "epson",
    shortDesc: "Reliable high-volume 24-pin dot matrix printer for business forms.",
    description: "A robust business printer for invoices, multipart forms and continuous stationery. It offers dependable long-life operation and straightforward USB connectivity.",
    basePrice: 68500, originalPrice: 72000, image: `${PRODUCT_ROOT}/1773129714167-epson-printers-lq-690ii-cover.webp`, gallery: [`${GALLERY_ROOT}/1773129721321-epson-printers-lq-690ii-picture-1.webp`, `${GALLERY_ROOT}/1773129721339-epson-printers-lq-690ii-picture-2.webp`, `${GALLERY_ROOT}/1773129721229-epson-printers-lq-690ii-picture-3.webp`], soldCount: 21, weight: 7.1,
    specs: { "Print Method": "24-pin Impact Dot Matrix", "Print Speed": "Up to 487 cps", Connectivity: "USB / Parallel", "Paper Paths": "Front / Rear / Top", Warranty: "1 Year" },
    variants: standardVariant("DEMO-PRN-EPS-001", 68500, 7, 61800),
  },
  {
    key: "chair", name: "Electron Valiant Ergonomic Gaming Chair", slug: "electron-valiant-ergonomic-gaming-chair", sku: "DEMO-CHR-ELE-001", categoryKey: "chair", brandKey: "electron",
    shortDesc: "Reclining gaming chair with adjustable support and durable upholstery.",
    description: "Designed for long gaming and work sessions, the Valiant offers adjustable height, recline, lumbar support and a stable metal base.",
    basePrice: 18500, originalPrice: 21000, image: `${PRODUCT_ROOT}/1773129366033-electron-gaming-chair-valiant-cover.webp`, gallery: [`${GALLERY_ROOT}/1773129372415-electron-gaming-chair-valiant-picture-1.webp`], soldCount: 44, weight: 18.5,
    specs: { Material: "PU Leather and Mesh", "Weight Capacity": "Up to 130kg", Recline: "90-150 degrees", Armrest: "2D Adjustable", Color: "Black / Red", Warranty: "1 Year" },
    variants: [
      { sku: "DEMO-CHR-ELE-001-RD", price: 18500, costPrice: 15100, stock: 11, options: { Color: "Black & Red" }, isDefault: true },
      { sku: "DEMO-CHR-ELE-001-BL", price: 18900, costPrice: 15400, stock: 8, options: { Color: "Black & Blue" } },
    ],
  },
  {
    key: "chair907", name: "Gamedias GC-907 Premium Gaming Chair", slug: "gamedias-gc-907-premium-gaming-chair", sku: "DEMO-CHR-GAM-001", categoryKey: "chair", brandKey: "gamedias",
    shortDesc: "Premium high-back chair with footrest and full recline.",
    description: "A supportive high-back gaming chair with a retractable footrest, adjustable recline and thick padding for extended sessions.",
    basePrice: 22900, originalPrice: 25500, image: `${PRODUCT_ROOT}/1772527712659-gc-907-01-500x500.webp`, soldCount: 28, weight: 20.5,
    specs: { Material: "Premium PU Leather", "Weight Capacity": "Up to 150kg", Recline: "90-180 degrees", Armrest: "Adjustable", Color: "Black", Warranty: "1 Year" },
    variants: standardVariant("DEMO-CHR-GAM-001-BLK", 22900, 6, 19200),
  },
  {
    key: "geyser", name: "Konka KD-60D1C1 60L Electric Water Heater", slug: "konka-kd-60d1c1-60l-water-heater", sku: "DEMO-APP-KON-001", categoryKey: "waterheater", brandKey: "konka",
    shortDesc: "60-litre electric water heater with safety protection.",
    description: "A family-size storage water heater with adjustable temperature, insulated tank and multiple safety protections for dependable daily use.",
    basePrice: 16900, originalPrice: 18500, image: `${PRODUCT_ROOT}/1773128954247-konka-geyser-kd-60d1c1-cover.webp`, soldCount: 35, weight: 21,
    specs: { Capacity: "60 Litres", Power: "2000W", "Temperature Range": "30-75°C", Protection: "Overheat and dry-heating protection", Warranty: "2 Years" },
    variants: standardVariant("DEMO-APP-KON-001-60L", 16900, 9, 14100),
  },
  {
    key: "tv", name: "TechVision 55-inch 4K Android Smart TV", slug: "techvision-55-inch-4k-android-smart-tv", sku: "DEMO-TV-TEC-001", categoryKey: "smarttv", brandKey: "techvision",
    shortDesc: "Large-screen 4K Android TV with HDR and built-in streaming.",
    description: "A cinematic 55-inch smart television with 4K resolution, HDR support, popular streaming apps and convenient wireless casting for the family living room.",
    basePrice: 58900, originalPrice: 64900, image: `${PRODUCT_ROOT}/1772430670432-TV11.jpg`, gallery: [`${GALLERY_ROOT}/1772430675825-TV11.jpg`, `${GALLERY_ROOT}/1772430675825-TV11.avif`], featured: true, soldCount: 52, weight: 13.8,
    specs: { Display: "55-inch 4K LED", Resolution: "3840 x 2160", "Operating System": "Android TV", Connectivity: "Wi-Fi / Bluetooth / HDMI / USB", Audio: "Dolby Audio", Warranty: "2 Years" },
    variants: standardVariant("DEMO-TV-TEC-001-55", 58900, 8, 51200),
  },
  {
    key: "drone", name: "SkyView X12 4K GPS Camera Drone", slug: "skyview-x12-4k-gps-camera-drone", sku: "DEMO-GAD-SKY-001", categoryKey: "drone", brandKey: "skyview",
    shortDesc: "Foldable GPS drone with stabilized 4K camera and return-to-home.",
    description: "A travel-friendly camera drone with GPS positioning, stable flight modes, live video and automatic return-to-home. A spare battery option extends shooting time.",
    basePrice: 18900, originalPrice: 21900, image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, gallery: [`${GALLERY_ROOT}/1772431239640-Drone1.jpg`, `${GALLERY_ROOT}/1772431239640-Drone14.jpg`, `${GALLERY_ROOT}/1772431239640-Drone2.jpg`], featured: true, soldCount: 39, weight: 0.48,
    specs: { Camera: "4K UHD", "Flight Time": "Up to 28 minutes", Connectivity: "5GHz Wi-Fi", Range: "Up to 1.2km", Features: "GPS / Return-to-home / Follow mode", Warranty: "6 Months" },
    variants: [
      { sku: "DEMO-GAD-SKY-001-1BAT", price: 18900, costPrice: 15300, stock: 14, options: { Package: "Single Battery" }, isDefault: true },
      { sku: "DEMO-GAD-SKY-001-2BAT", price: 21400, costPrice: 17400, stock: 9, options: { Package: "Dual Battery" } },
    ],
  },
  {
    key: "drone_s8", name: "SkyView S8 Mini Foldable Camera Drone", slug: "skyview-s8-mini-foldable-camera-drone", sku: "DEMO-GAD-SKY-002", categoryKey: "drone", brandKey: "skyview",
    shortDesc: "Compact beginner drone with dual camera, altitude hold and one-key return.",
    description: "A lightweight foldable camera drone designed for first-time pilots and casual aerial photography. Altitude hold, headless mode and one-key return make everyday flying simple, while the included propeller guards add confidence indoors.",
    basePrice: 7490, originalPrice: 8490, image: `${GALLERY_ROOT}/1772431239640-Drone1.jpg`, gallery: [`${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, `${GALLERY_ROOT}/1772431239640-Drone14.jpg`, `${GALLERY_ROOT}/1772431239640-Drone2.jpg`], soldCount: 74, weight: 0.21,
    specs: { Camera: "Dual HD Camera", "Flight Time": "Up to 18 minutes", Connectivity: "2.4GHz Wi-Fi", Range: "Up to 150m", Features: "Altitude hold / Headless mode / One-key return", Warranty: "3 Months" },
    variants: [
      { sku: "DEMO-GAD-SKY-002-1BAT", price: 7490, costPrice: 5900, stock: 22, options: { Package: "Single Battery" }, isDefault: true },
      { sku: "DEMO-GAD-SKY-002-2BAT", price: 8490, costPrice: 6650, stock: 16, options: { Package: "Dual Battery" } },
    ],
  },
  {
    key: "drone_x15", name: "SkyView X15 Pro 4K GPS Camera Drone", slug: "skyview-x15-pro-4k-gps-camera-drone", sku: "DEMO-GAD-SKY-003", categoryKey: "drone", brandKey: "skyview",
    shortDesc: "4K GPS drone with brushless motors, smart tracking and extended range.",
    description: "The X15 Pro combines stable GPS positioning, efficient brushless motors and intelligent tracking modes for smooth outdoor footage. Its foldable body and carrying case make it a capable travel companion.",
    basePrice: 26900, originalPrice: 29900, image: `${GALLERY_ROOT}/1772431239640-Drone14.jpg`, gallery: [`${GALLERY_ROOT}/1772431239640-Drone2.jpg`, `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, `${GALLERY_ROOT}/1772431239640-Drone1.jpg`], featured: true, soldCount: 58, weight: 0.56,
    specs: { Camera: "4K UHD EIS", "Flight Time": "Up to 32 minutes", Connectivity: "5GHz Wi-Fi", Range: "Up to 2km", Features: "GPS / Follow mode / Waypoint flight / Return-to-home", Warranty: "6 Months" },
    variants: [
      { sku: "DEMO-GAD-SKY-003-1BAT", price: 26900, costPrice: 22100, stock: 11, options: { Package: "Single Battery" }, isDefault: true },
      { sku: "DEMO-GAD-SKY-003-FLYMORE", price: 30900, costPrice: 25400, stock: 7, options: { Package: "Fly More Combo" } },
    ],
  },
  {
    key: "drone_x20", name: "SkyView X20 Explorer 3-Axis Gimbal Drone", slug: "skyview-x20-explorer-gimbal-drone", sku: "DEMO-GAD-SKY-004", categoryKey: "drone", brandKey: "skyview",
    shortDesc: "Long-range camera drone with a 3-axis gimbal and obstacle sensing.",
    description: "Built for enthusiast aerial creators, the X20 Explorer uses a three-axis mechanical gimbal for steady footage and front obstacle sensing for safer flight. Long battery life and GPS-assisted modes support extended outdoor shoots.",
    basePrice: 42900, originalPrice: 46900, image: `${GALLERY_ROOT}/1772431239640-Drone2.jpg`, gallery: [`${GALLERY_ROOT}/1772431239640-Drone14.jpg`, `${GALLERY_ROOT}/1772431239640-Drone1.jpg`, `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`], featured: true, soldCount: 27, weight: 0.72,
    specs: { Camera: "4K UHD with 3-axis gimbal", "Flight Time": "Up to 38 minutes", Connectivity: "Dual-band Wi-Fi", Range: "Up to 4km", Features: "Obstacle sensing / GPS / Smart return / Point of interest", Warranty: "1 Year" },
    variants: [
      { sku: "DEMO-GAD-SKY-004-STD", price: 42900, costPrice: 35800, stock: 8, options: { Package: "Standard Kit" }, isDefault: true },
      { sku: "DEMO-GAD-SKY-004-CREATOR", price: 48900, costPrice: 40500, stock: 5, options: { Package: "Creator Combo" } },
    ],
  },
  {
    key: "drone_aerocam_v9", name: "AeroCam V9 Dual Camera Brushless Drone", slug: "aerocam-v9-dual-camera-brushless-drone", sku: "DEMO-GAD-AERO-001", categoryKey: "drone", brandKey: "aerocam",
    shortDesc: "Portable brushless drone with dual cameras and optical-flow positioning.",
    description: "A compact aerial camera platform with quiet brushless motors and optical-flow positioning for stable low-altitude flight. The dual-camera setup and gesture controls are suited to travel clips and family events.",
    basePrice: 11900, originalPrice: 13500, image: `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, gallery: [`${GALLERY_ROOT}/1772431239640-Drone1.jpg`, `${GALLERY_ROOT}/1772431239640-Drone2.jpg`, `${GALLERY_ROOT}/1772431239640-Drone14.jpg`], soldCount: 63, weight: 0.32,
    specs: { Camera: "Dual 2K Camera", "Flight Time": "Up to 22 minutes", Connectivity: "2.4GHz Wi-Fi", Range: "Up to 300m", Features: "Optical flow / Gesture photo / Brushless motors", Warranty: "6 Months" },
    variants: [
      { sku: "DEMO-GAD-AERO-001-2BAT", price: 11900, costPrice: 9500, stock: 18, options: { Package: "Dual Battery" }, isDefault: true },
      { sku: "DEMO-GAD-AERO-001-3BAT", price: 13200, costPrice: 10500, stock: 10, options: { Package: "Triple Battery" } },
    ],
  },
  {
    key: "drone_aerocam_p16", name: "AeroCam P16 GPS 4K Smart Camera Drone", slug: "aerocam-p16-gps-4k-smart-camera-drone", sku: "DEMO-GAD-AERO-002", categoryKey: "drone", brandKey: "aerocam",
    shortDesc: "GPS-assisted 4K drone with orbit mode, follow-me and automatic return.",
    description: "The P16 is a balanced mid-range camera drone with GPS-assisted stability and automated flight modes. Orbit, follow-me and fail-safe return features help creators capture repeatable aerial shots with less manual control.",
    basePrice: 22490, originalPrice: 24900, image: `${GALLERY_ROOT}/1772431239640-Drone1.jpg`, gallery: [`${GALLERY_ROOT}/1772431239640-Drone14.jpg`, `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`, `${GALLERY_ROOT}/1772431239640-Drone2.jpg`], featured: true, soldCount: 46, weight: 0.51,
    specs: { Camera: "4K UHD", "Flight Time": "Up to 30 minutes", Connectivity: "5GHz Wi-Fi", Range: "Up to 1.5km", Features: "GPS / Orbit mode / Follow-me / Fail-safe return", Warranty: "6 Months" },
    variants: [
      { sku: "DEMO-GAD-AERO-002-STD", price: 22490, costPrice: 18400, stock: 13, options: { Package: "Standard Kit" }, isDefault: true },
      { sku: "DEMO-GAD-AERO-002-COMBO", price: 25490, costPrice: 20800, stock: 8, options: { Package: "Travel Combo" } },
    ],
  },
  {
    key: "drone_aerocam_mini", name: "AeroCam Mini 4K Pocket Camera Drone", slug: "aerocam-mini-4k-pocket-camera-drone", sku: "DEMO-GAD-AERO-003", categoryKey: "drone", brandKey: "aerocam",
    shortDesc: "Sub-250g pocket drone with stabilized 4K video and quick-launch modes.",
    description: "Designed for portability, the AeroCam Mini folds into a compact travel size while offering stabilized 4K recording and useful quick-launch shooting modes. Its low take-off weight makes it convenient for everyday trips.",
    basePrice: 32900, originalPrice: 35900, image: `${GALLERY_ROOT}/1772431239640-Drone14.jpg`, gallery: [`${GALLERY_ROOT}/1772431239640-Drone2.jpg`, `${GALLERY_ROOT}/1772431239640-Drone1.jpg`, `${PRODUCT_ROOT}/1772431232261-Drone2.jpg`], soldCount: 34, weight: 0.249,
    specs: { Camera: "4K Stabilized Camera", "Flight Time": "Up to 31 minutes", Connectivity: "Dual-band Wi-Fi", Range: "Up to 3km", Features: "Quick shots / GPS hover / Automatic return / Panorama", Warranty: "1 Year" },
    variants: [
      { sku: "DEMO-GAD-AERO-003-STD", price: 32900, costPrice: 27500, stock: 9, options: { Package: "Standard Kit" }, isDefault: true },
      { sku: "DEMO-GAD-AERO-003-FLYMORE", price: 38900, costPrice: 32400, stock: 6, options: { Package: "Fly More Combo" } },
    ],
  },
];

export const STOREFRONT_BANNERS = [
  { title: "Storefront Demo | Laptop & PC Festival", subtitle: "Power up your work and play", description: "Explore featured laptops, desktops and gaming gear with demo-ready pricing.", image: "/upload/banners/1772684171822-image-asus-gaming-fest-1772102451.webp", mobileImage: "/upload/banners/1772684171822-image-asus-gaming-fest-1772102451.webp", buttonText: "Shop Computers", buttonLink: "/products?category=desktop-pc", position: 1, type: "HERO" as const },
  { title: "Storefront Demo | Corporate Technology", subtitle: "Business purchase support", description: "Reliable devices and accessories for growing teams.", image: "/upload/banners/1772524720708-s2.webp", mobileImage: "/upload/banners/1772524720708-s2.webp", buttonText: "View Laptops", buttonLink: "/products?category=laptop", position: 2, type: "HERO" as const },
  { title: "Storefront Demo | Components Deal", subtitle: "Build your next PC", description: "Processors, SSDs, power supplies and displays in one catalog.", image: "/upload/banners/1772524740986-s3.webp", mobileImage: "/upload/banners/1772524740986-s3.webp", buttonText: "Browse Components", buttonLink: "/products?category=processor", position: 3, type: "HERO" as const },
];

export const STOREFRONT_REVIEW_COMMENTS = [
  "Product quality and packaging were excellent. The demo delivery was fast and the item matched the description.",
  "Good value for the price. Setup was straightforward and the product has performed reliably so far.",
];

export const STOREFRONT_QUESTIONS = [
  { question: "Is this product covered by an official warranty?", answer: "Yes. The warranty period shown in the specification applies, and the invoice is required for a claim." },
  { question: "Can I pay cash on delivery?", answer: "Cash on delivery is available in supported areas. Availability is confirmed during checkout." },
  { question: "How quickly can this be delivered inside Dhaka?", answer: "In-stock items are normally delivered inside Dhaka within one to two business days." },
  { question: "Is the displayed price inclusive of the standard configuration?", answer: "Yes. The displayed price is for the selected variant; optional upgrades show their own price before adding to cart." },
];
